channels:
- conda-forge
- main
dependencies:
- beautifulsoup4=4.9.3
- black=20.8b1
- click=7.1.2
- codecov=2.1.10
- dill=0.3.3
- gcsfs=0.7.1
- geckodriver=0.28.0
- ipython=7.19.0
- leveldb=1.22
- multiprocess=0.70.11.1
- mypy=0.790
- nodejs=14.15.1
- pandas=1.1.5
- pillow=8.0.1
- pip=20.3.1
- pre-commit=2.9.3
- psutil=5.7.3
- pyarrow=2.0.0
- pytest-cov=2.10.1
- pytest=6.1.2
- python=3.8.6
- pyvirtualdisplay=0.2.5
- redis-py=3.5.3
- s3fs=0.5.1
- selenium=3.141.0
- sentry-sdk=0.19.5
- tabulate=0.8.7
- tblib=1.6.0
- wget=1.20.1
- pip:
  - dataclasses-json==0.5.2
  - domain-utils==0.7.1
  - jsonschema==3.2.0
  - plyvel==1.3.0
name: openwpm
